Improve PR template
sigstore/.github pull request #5
Opened 2022-02-03 09:49 UTC by lukehinds

Serveral changes are implemented here.

* Request that an issue first be raised
* Ask for more details on how to test
* Remove references to mattermost
* Add documentation section

Signed-off-by: Luke Hinds <luke@redhat.com>

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2022-02-03 09:57 UTC, lukehinds commented
@cpanato

2022-02-03 09:59 UTC, cpanato submitted a review, later dismissed
thanks for the updates lgtm

2022-02-03 14:58 UTC, mbestavros requested changes
Looks good to me, apart from a small typo.

2022-02-03 14:58 UTC, mbestavros commented on pull_request_template.md
> +- This PR requires an isssue. If it is a new feature, the issue should proceed the PR and will have allowed sufficent time for discussions to take place. Pleases use
"isssue" -> "issue"

2022-07-01 21:30 UTC, mbestavros approved these changes

2022-07-01 21:31 UTC, merged